config/routes.rb
Spree::Core::Engine.routes.draw do

	namespace :admin do
		resources :package_types
	end
end

app/models/spree/package.rb
module Spree
	class Package < Spree::Base
	  belongs_to :package_type
	  belongs_to :user
	  has_many :package_variants
	end
end

app/models/spree/package_type.rb
module Spree
	class PackageType < Spree::Base
		has_many :package_type_taxons
		has_many :packages
	end
end

app/models/spree/package_type_taxon.rb
module Spree
	class PackageTypeTaxon < Spree::Base
	  belongs_to :package_type
	  belongs_to :taxon
	end
end

app/models/spree/package_variant.rb
module Spree
	class PackageVariant < Spree::Base
	  belongs_to :package
	  belongs_to :variant
	end
end

app/models/spree/taxon_decorator.rb
module Spree
	Taxon.instance_eval do
		has_many :package_type_taxons
	end
end

app/models/spree/user_decorator.rb
module Spree
	User.instance_eval do
		has_many :packages
	end
end

app/models/spree/variant_decorator.rb
module Spree
	Variant.instance_eval do
		has_many :package_variants
	end
end

app/controllers/spree/admin/package_types_controller.rb
module Spree
	module Admin
		class PackageTypesController < ResourceController
			def index
				@collection = PackageType.all
			end

			def show
			end

			def new
				@package_type = PackageType.new
				@taxons = Taxon.all
			end

			def create
				package_type = PackageType.create(name: params[:name])
				taxons = params[:taxons]
				taxons.each do |taxon_id|
					PackageTypeTaxon.create(package_type: package_type, taxon: Taxon.find(taxon_id))
				end
				redirect_to admin_package_types_path
			end

			def edit
			end

			def update
			end

			def destroy
				PackageType.find(params[:id]).destroy
				redirect_to admin_package_types_path
			end

		end
	end
end

app/views/spree/admin/package_types/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::PackageType) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_package), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_product' } %>
<% end %>

<% if @collection.any? %>
  <table class="table" id="listing_products">
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th><%= Spree.t(:status) %></th>
        <th><%= "Package Name" %></th>
        <th class="text-center"><%= "No. of Items Incl." %></th>
        <th class="text-center"><%= "No. of Packages Made" %></th>
        <th data-hook="admin_products_index_header_actions" class="text-center"></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |package_type| %>
          <tr <%# "style='color: red;'" if package_type.deleted? %> id="<%= spree_dom_id package_type %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="status"><%# available_status(package_type) %> </td>
            <td><%= link_to package_type.try(:name), admin_package_type_path(package_type) %></td>
            <td class="text-center"><%= package_type.package_type_taxons.count rescue '' %></td>
            <td class="text-center"><%= package_type.packages.count rescue '' %></td>
            <td class="actions actions-3 text-right" data-hook="admin_products_index_row_actions">
              <%= link_to_edit package_type, no_text: true, class: 'edit' if can?(:edit, package_type) %>
              <%# link_to_clone package_type, no_text: true, class: 'clone' if can?(:clone, package_type) %>
              <%= link_to_delete package_type, no_text: true if can?(:delete, package_type) %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::PackageType)) %>,
    <%= link_to Spree.t(:add_one), new_admin_package_type_path %>!
  </div>
<% end %>

app/views/spree/admin/package_types/new.html.erb
<% content_for :page_title do %>
  <%= link_to "Package", admin_package_types_path %> /
  <%= Spree.t(:new_package) %>
<% end %>

<%= form_tag("/admin/package_types", method: :post) do %>
	<%= field_set_tag nil, class: "form-group" do %>
		<%= label_tag "name", "Package Name" %> <span class="required">*</span>
		<%= text_field_tag "name", nil, class: 'form-control title' %>
	<% end %>

	<%= field_set_tag nil, class: "form-group" do %>
		<%= label_tag "taxons", "Taxons" %> <span class="required">*</span>
		<%= select_tag "taxons", options_from_collection_for_select(@taxons, "id", "name"), multiple: true, id: "select-multiple-taxons", class: "form-control title" %>
	<% end %>
  <%= render partial: 'spree/admin/shared/new_resource_links' %>
<% end %>


<style>
	#select-multiple-taxons {
		height: 200px;
		width: 100px;
	}
</style>

app/views/spree/admin/package_types/show.html.erb
<h1>Package</h1>